# Copyright 2025
#
# Licensed under a BSD-style license <LICENSE-BSD>, Apache License, Version 2.0
# <LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0>, or the MIT
# license <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your option.
# This file may not be copied, modified, or distributed except according to
# those terms.

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      # The trailing space instructs dependabot not to insert a colon between
      # the prefix and the rest of the message.
      prefix: "[CI] "
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "[deps] "
    ignore:
      # Block all major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      patch-updates:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "@biomejs/*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
          - "@biomejs/*"
        update-types:
          - "minor"
